### ISSUE TITLE
Nord Atom UI codebase migration

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/northem-dark-atom-ui#4]
**Tasks**
  - [x] Adapt core style from the Nord Atom UI codebase
  - [x] Adapt all supported package styles from the Nord Atom UI codebase
  - [x] Implement the theme settings feature
    - [x] Implement the `main.coffee` library
    - [x] Implement `specs`
    - [x] Implement config schema into the `package.json`

This issue is part of the [Version 2.0.0](https://github.com/arcticicestudio/northem-dark-atom-syntax/milestone/1)  milestone tracked in the backlog issue #3.
